### PR TITLE
Bug 1366025 - Shavar domain blocklist updates for Flash Study, week 3. r=bytesized

### PR DESCRIPTION
**Pull request by felipc**
PLEASE DON'T MERGE TO PROD YET.  We will test this on staging first and when QA gives a thumbs up we'll push to prod.

Add URLs for the Week 3 of the flash study, as specified on bug 1366025.

### CODE REVIEW

**Comment by felipc** [comment]
I don't know why the Request Review UI doesn't show up for me here :(
@bytesized, can you review?

**Review by bytesized — CHANGES_REQUESTED** [review]
Bug 1366025 indicates that Paypal should be added to the blocklist, but you have added it to the exceptions list.

**Review by bytesized — APPROVED** [review]
Looks good to me.

**Comment by groovecoder** [comment]
Sent https://github.com/mozilla-services/shavar-list-creation-config/pull/19 to make the stage list-creation script use this branch.

**Comment by groovecoder** [comment]
Merged. Should be live on production within 30m.

**Pull request merged**
