### PR TITLE
Bug 1352224 - Add initial entries to flashsubdoc list for the Telemetry Experiments on Nightly

### PR DESCRIPTION
**Pull request by felipc**
Bug 1352224 - Add initial entries to flashsubdoc list for the Telemetry Experiments on Nightly.

The list includes the sentinel nightly.flashstudy.example.com entry that will allow the client
to make sure that this list update has been received.

### CODE REVIEW

**Review by bytesized — APPROVED** [review]
This looks good to me.

**Comment by groovecoder** [comment]
I pointed my local `shavar-list-creation/lists2safebrowsing.py` script at this new `flashsubdoc.txt` file and it ran fine. 2274 new items in the `flash-subdoc` list.

```
(shavar-list-creation)groovecoder:shavar-list-creation lcrouch$ ./lists2safebrowsing.py
PSL updated
last-modified: Tue, 04 Apr 2017 20:20:24 GMT
Tracking protection(tracking-protection-testing): publishing 1718 items; file size 54998
Tracking protection(tracking-protection-base): publishing 1717 items; file size 54966
Tracking protection(tracking-protection-baseeff): publishing 1 items; file size 51
Tracking protection(tracking-protection-basew3c): publishing 0 items; file size 18
Tracking protection(tracking-protection-content): publishing 519 items; file size 16630
Tracking protection(tracking-protection-contenteff): publishing 0 items; file size 18
Tracking protection(tracking-protection-contentw3c): publishing 0 items; file size 18
Entity whitelist(entity-whitelist): publishing 9723 items; file size 311159
Entity whitelist(entity-whitelist-testing): publishing 9678 items; file size 309719
Tracking protection(tracking-protection-standard): publishing 1717 items; file size 54966
Tracking protection(tracking-protection-full): publishing 2236 items; file size 71574
Plugin blocklist(plugin-blocklist): publishing 94 items; file size 3029
Plugin blocklist(plugin-blocklist-experiment): publishing 132 items; file size 4245
Plugin blocklist(flash-blocklist): publishing 1 items; file size 51
Plugin blocklist(flash-exceptions): publishing 1 items; file size 51
Plugin blocklist(flash-allow): publishing 1 items; file size 51
Plugin blocklist(flash-allow-exceptions): publishing 1 items; file size 51
Plugin blocklist(flash-subdoc): publishing 2274 items; file size 72790
Plugin blocklist(flash-subdoc-exceptions): publishing 1 items; file size 51
Entity whitelist(staging-entity-whitelist): publishing 9723 items; file size 311159
Tracking protection(staging-tracking-protection-standard): publishing 1717 items; file size 54966
Tracking protection(staging-tracking-protection-full): publishing 2236 items; file size 71574
No new data to publish for tracking-protection-testing
No new data to publish for tracking-protection-base
No new data to publish for tracking-protection-baseeff
No new data to publish for tracking-protection-basew3c
No new data to publish for tracking-protection-content
No new data to publish for tracking-protection-contenteff
No new data to publish for tracking-protection-contentw3c
No new data to publish for entity-whitelist
No new data to publish for entity-whitelist-testing
No new data to publish for tracking-protection-standard
No new data to publish for tracking-protection-full
No new data to publish for plugin-blocklist
No new data to publish for plugin-blocklist-experiment
No new data to publish for flash-blocklist
No new data to publish for flash-exceptions
No new data to publish for flash-allow
No new data to publish for flash-allow-exceptions
No new data to publish for flash-subdoc
No new data to publish for flash-subdoc-exceptions
No new data to publish for staging-entity-whitelist
No new data to publish for staging-tracking-protection-standard
No new data to publish for staging-tracking-protection-full
```

**Comment by groovecoder** [comment]
And the ShavarListCreationProd job worked and uploaded the new contents to S3 ...
```
...
Plugin blocklist(flash-subdoc): publishing 2274 items; file size 72790
Plugin blocklist(flash-subdoc-exceptions): publishing 1 items; file size 51
Entity whitelist(staging-entity-whitelist): publishing 9723 items; file size 311159
Tracking protection(staging-tracking-protection-standard): publishing 1717 items; file size 54966
Tracking protection(staging-tracking-protection-full): publishing 2236 items; file size 71574
No new data to publish for tracking-protection-base
No new data to publish for tracking-protection-baseeff
No new data to publish for tracking-protection-basew3c
No new data to publish for tracking-protection-content
No new data to publish for tracking-protection-contenteff
No new data to publish for tracking-protection-contentw3c
No new data to publish for entity-whitelist
No new data to publish for tracking-protection-standard
No new data to publish for tracking-protection-full
No new data to publish for plugin-blocklist
No new data to publish for plugin-blocklist-experiment
No new data to publish for flash-blocklist
No new data to publish for flash-exceptions
No new data to publish for flash-allow
No new data to publish for flash-allow-exceptions
Uploaded to s3: flash-subdoc
...
```

**Comment by groovecoder** [comment]
So, Firefox clients should now be able to get the new flash-subdoc list contents.

**Comment by felipc** [comment]
Thanks, all!

**Pull request merged**
