### PR TITLE
Bug 1363792 - Add URLs for week 2 of the Flash Study

### PR DESCRIPTION
**Pull request by felipc**
PLEASE DONT MERGE TO PROD yet.  We need this only on staging while QA can test it.

### CODE REVIEW

**Comment by felipc** [comment]
@bytesized can you review?

**Review by bytesized — APPROVED** [review]
This looks good to me

**Comment by groovecoder** [comment]
I pointed the stage shavar list creation job at felipc's repo, and the output looks right:
```
Plugin blocklist(flash-blocklist): publishing 5 items; file size 180
Plugin blocklist(flash-exceptions): publishing 2 items; file size 83
```
Should I leave this open? Do we plan to make these changes in production too?

**Comment by felipc** [comment]
Yep, let's keep this open. QA will test the behavior of some websites with this list, and pending their sign off, we will want to merge this into production.

**Comment by groovecoder** [comment]
And production output looks right, too:
```
Plugin blocklist(flash-blocklist): publishing 5 items; file size 180
Plugin blocklist(flash-exceptions): publishing 2 items; file size 83
...
Plugin blocklist(flash-subdoc): publishing 2287 items; file size 73206
...
Uploaded to s3: flash-blocklist
Uploaded to s3: flash-exceptions
...
Uploaded to s3: flash-subdoc
```

**Pull request merged**
